# golangci-lint configuration file
# see: https://golangci-lint.run/usage/configuration/

version: "2"
linters:
  enable:
    - copyloopvar
    - dupword
    - durationcheck
    - ginkgolinter
    - gocritic
    - loggercheck
    - misspell
    - perfsprint
    - revive
    - unconvert
  settings:
    gocritic:
      enabled-checks:
        - dupImport
      disabled-checks:
        - appendAssign
        - exitAfterDefer
    govet:
      enable:
        - nilness
    perfsprint:
      int-conversion: false
      errorf: true
      sprintf1: false
      strconcat: false
    revive:
      enable-all-rules: false
      rules:
        - name: empty-lines
        - name: var-naming
        - name: redundant-import-alias
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        # TODO(#768): Drop when incrementing the API version.
        text: 'SA1019: constants.QueueAnnotation is deprecated'
      - linters:
          - staticcheck
        text: 'SA1019: j.Status.State is deprecated: the State field is replaced by the Conditions field.'
      - linters:
          - staticcheck
        text: 'SA1019: rayCluster.Status.State is deprecated: the State field is replaced by the Conditions field.'
    paths:
      - bin
      - third_party$
      - builtin$
      - examples$
issues:
  # Show all issues from a linter
  max-issues-per-linter: 0
  # Show all issues with the same text
  max-same-issues: 0
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(sigs.k8s.io/kjob) # Custom section: groups all imports with the specified Prefix.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports.
  exclusions:
    generated: lax
    paths:
      - bin
      - third_party$
      - builtin$
      - examples$
