/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	apisv1alpha1 "sigs.k8s.io/kjob/apis/v1alpha1"
	scheme "sigs.k8s.io/kjob/client-go/clientset/versioned/scheme"
)

// JobSetTemplatesGetter has a method to return a JobSetTemplateInterface.
// A group's client should implement this interface.
type JobSetTemplatesGetter interface {
	JobSetTemplates(namespace string) JobSetTemplateInterface
}

// JobSetTemplateInterface has methods to work with JobSetTemplate resources.
type JobSetTemplateInterface interface {
	Create(ctx context.Context, jobSetTemplate *apisv1alpha1.JobSetTemplate, opts v1.CreateOptions) (*apisv1alpha1.JobSetTemplate, error)
	Update(ctx context.Context, jobSetTemplate *apisv1alpha1.JobSetTemplate, opts v1.UpdateOptions) (*apisv1alpha1.JobSetTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apisv1alpha1.JobSetTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*apisv1alpha1.JobSetTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apisv1alpha1.JobSetTemplate, err error)
	JobSetTemplateExpansion
}

// jobSetTemplates implements JobSetTemplateInterface
type jobSetTemplates struct {
	*gentype.ClientWithList[*apisv1alpha1.JobSetTemplate, *apisv1alpha1.JobSetTemplateList]
}

// newJobSetTemplates returns a JobSetTemplates
func newJobSetTemplates(c *KjobctlV1alpha1Client, namespace string) *jobSetTemplates {
	return &jobSetTemplates{
		gentype.NewClientWithList[*apisv1alpha1.JobSetTemplate, *apisv1alpha1.JobSetTemplateList](
			"jobsettemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apisv1alpha1.JobSetTemplate { return &apisv1alpha1.JobSetTemplate{} },
			func() *apisv1alpha1.JobSetTemplateList { return &apisv1alpha1.JobSetTemplateList{} },
		),
	}
}
